In [101]:
from bs4 import BeautifulSoup

import urllib
import urllib.request
import re
import pandas as pd

In [102]:
with urllib.request.urlopen('https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States') as response:
    html = response.read()

In [103]:
soup = BeautifulSoup(html, "lxml")
type(soup)

bs4.BeautifulSoup

In [104]:
th= soup.find_all('th')
states = []
for tag_th in th:
            a = tag_th.find_all('a')
            for tag_a in a:
                states.append(tag_a.get_text())
print("['"+"', '".join(states)+"']")

['Political divisions ofthe United States', 'First level', 'postal abbreviation', '[8]', '[A]', '[10]', '[11]', '[11]', '[11]', 'Numberof Reps.', '[12]', 'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', '[B]', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', '[B]', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', '[B]', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', '[B]', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'postal abbreviation', '[8]', '[10]', '[11]', '[11]', '[11]', 'Numberof Reps.', 'District of Columbia', 'postal abbreviation', '[8]', 'Capital', 'Acquired', '[15]', '[16]', '[10]', '[17]', '[11]', '[11]', '[11]', 'Numberof Reps.', 'American Samoa', 'Guam', 'Northern Mariana Islands', 'Puerto Rico', 'U.S. Virgin Islands', 'Acquired', '[15]', '[16]', '[G]', 'Baker Island', '[24]', 'Howland Island', '[24]', 'Jarvis Island', '[25]', 'Johnston Atoll', '[26]', 'Kingman Reef', '[27]', 'Midway Atoll', '[H]', '[29]', 'Navassa Island', '[30]', 'Palmyra Atoll', '[J]', '[32]', 'Wake Island', '[K]', '[33]', '[15]', '[35]', '[35]', '[35]', 'Bajo Nuevo Bank (Petrel Island)', '[15]', 'Serranilla Bank', '[15]', 'v', 't', 'e', 'Federal district', 'Insular areas', 'Outlying islands', 'Indian reservations', 'v', 't', 'e', 'United States state-related lists', 'v', 't', 'e', 'United States', 'History', 'Geography', 'Politics', 'Federal', 'Legislative', 'Judicial', 'Law', 'Intelligence', 'Uniformed', 'Economy', 'Society', 'Culture', 'Social class', 'v', 't', 'e', 'Federal district', 'Insular areas', 'v', 't', 'e', 'Sovereign states', 'Dependencies', 'territories']

In [105]:
states = [item for item in states if len(item) > 3 ]
states = states[9:59]
print("['"+"', '".join(states)+"']", len(states))

['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'] 50

In [106]:
td= soup.find_all('td')
population = []
for tag_td in td:
            div = tag_td.find_all('div')
            for tag_div in div:
                population.append(tag_div.get_text())
print("['"+"', '".join(population[:101])+"']")

['vte', '5,024,279', '7', '733,391', '1', '7,151,502', '9', '3,011,524', '4', '39,538,223', '52', '5,773,714', '8', '3,605,944', '5', '989,948', '1', '21,538,187', '28', '10,711,908', '14', '1,455,271', '2', '1,839,106', '2', '12,812,508', '17', '6,785,528', '9', '3,190,369', '4', '2,937,880', '4', '4,505,836', '6', '4,657,757', '6', '1,362,359', '2', '6,177,224', '8', '7,029,917', '9', '10,077,331', '13', '5,706,494', '8', '2,961,279', '4', '6,154,913', '8', '1,084,225', '2', '1,961,504', '3', '3,104,614', '4', '1,377,529', '2', '9,288,994', '12', '2,117,522', '3', '20,201,249', '26', '10,439,388', '14', '779,094', '1', '11,799,448', '15', '3,959,353', '5', '4,237,256', '6', '13,002,700', '17', '1,097,379', '2', '5,118,425', '7', '886,667', '1', '6,910,840', '9', '29,145,505', '38', '3,271,616', '4', '643,077', '1', '8,631,393', '11', '7,705,281', '10', '1,793,716', '2', '5,893,718', '8', '576,851', '1']

In [107]:
population = population[:101]
population = [item.replace(',', '') for item in population if len(item) > 4]
print("['"+"', '".join(population)+"']")

['5024279', '733391', '7151502', '3011524', '39538223', '5773714', '3605944', '989948', '21538187', '10711908', '1455271', '1839106', '12812508', '6785528', '3190369', '2937880', '4505836', '4657757', '1362359', '6177224', '7029917', '10077331', '5706494', '2961279', '6154913', '1084225', '1961504', '3104614', '1377529', '9288994', '2117522', '20201249', '10439388', '779094', '11799448', '3959353', '4237256', '13002700', '1097379', '5118425', '886667', '6910840', '29145505', '3271616', '643077', '8631393', '7705281', '1793716', '5893718', '576851']

In [108]:
PDstates = pd.DataFrame(states, columns=['State'])
PDpopulation = pd.DataFrame(population, columns=['Population'])
table = pd.concat([PDstates, PDpopulation], axis=1)

In [109]:
table

             State Population
0          Alabama    5024279
1           Alaska     733391
2          Arizona    7151502
3         Arkansas    3011524
4       California   39538223
5         Colorado    5773714
6      Connecticut    3605944
7         Delaware     989948
8          Florida   21538187
9          Georgia   10711908
10          Hawaii    1455271
11           Idaho    1839106
12        Illinois   12812508
13         Indiana    6785528
14            Iowa    3190369
15          Kansas    2937880
16        Kentucky    4505836
17       Louisiana    4657757
18           Maine    1362359
19        Maryland    6177224
20   Massachusetts    7029917
21        Michigan   10077331
22       Minnesota    5706494
23     Mississippi    2961279
24        Missouri    6154913
25         Montana    1084225
26        Nebraska    1961504
27          Nevada    3104614
28   New Hampshire    1377529
29      New Jersey    9288994
30      New Mexico    2117522
31        New York   20201249
32  North Carolina   10439388
33    North Dakota     779094
34            Ohio   11799448
35        Oklahoma    3959353
36          Oregon    4237256
37    Pennsylvania   13002700
38    Rhode Island    1097379
39  South Carolina    5118425
40    South Dakota     886667
41       Tennessee    6910840
42           Texas   29145505
43            Utah    3271616
44         Vermont     643077
45        Virginia    8631393
46      Washington    7705281
47   West Virginia    1793716
48       Wisconsin    5893718
49         Wyoming     576851

In [110]:
table.to_csv('us_info.csv', index=False)